### ISSUE TITLE
How to create game LAN game?

### ISSUE THREAD

**Issue by asylumexp** [kres0345/ChessGame#14]
Hello,

I know this isn't typically the way to ask for support, but obviously seeing as it is a project, support or even a readme isn't in here.

Just wanting to ask because I attempted to start a LAN game with someone else who was on the network, we were both running the 1.0 release from releases, but we attempted to put both our IPs into the boxes but both times it stopped responding.

Most likely we aren't inputting them properly, but there really much of indication of what we were supposed to do. 

Any help with this would be appreciated, thanks!

**Comment by krestenlaust** [comment]
Yes of course! It is quite confusing the way it was designed.

It is intended that both participants select the player type 'local' as the color they are playing as, and then the networking option as the other player.

Both players IP field should contain the local IP of the White player. This is because for the White, this is the hosting IP, and for the Black this is where it connects.

For example, you are white-side and your friend plays as black-side, you should then have White as local, and Black as Networked. Then your friend should have Black as local, and White as networked. Then your network field should have Whites local IP, and so should player White.

Hope this helps, either way I'll be updating the documentation, or look into fixing a potential issue with networked.

Right now I'm on mobile, but I can send screenshots if needed.

Thanks for showing interest in the project!

**Comment by krestenlaust** [comment]
Feel free to add suggestions as to what should be documented, #15

**Comment by srcoggin** [comment]
didnt wok

**Comment by asylumexp** [comment]
> didnt wok

ignore srcoggin here he just replied and didn't give any context.

Think network is blocking LAN connections so it doesn't seem like there's anything we can do.

Thanks for your help though!

**Comment by krestenlaust** [comment]
I've created a readme now (#15), with screenshots of what the settings are supposed to say. It turns out I forgot a few things about the networking. Firstly, the black team is host, and secondly, the hosts match is supposed to be started first (for the server to start) and then it's going to stall (the UI is going to be stuck) until the white player has connected. Also, both IP fields need to contain the black players IP.

I've included this in the readme as well. I've also added an issue relating to the fact that the UI is frozen (#20), hope it makes it more clear.
